### ISSUE TITLE
wishes

### ISSUE THREAD

**Issue by Micha-Btz** [oleksiykovtun/Pics-on-Tumblr#1]
hi there,

i use your app for some time now and i like it very much. Since using i have 2 wishes.

1. the app should remember how many columns i have used an least
2. add the possibility to save pictures to the phone.

thanks Mich

**Comment by oleksiykovtun** [comment]
Hi. These 2 features are added. Also in Settings you can turn off remembering the number of columns.

**Comment by Micha-Btz** [comment]
thanks a lot. Wokrs great.
